import Link from 'next/link'
import { ArrowUpRight, CalendarDays, CheckCircle2, Clock3, FileText, Plus, TrendingUp } from 'lucide-react'
import { AppShell, PageHeader, StatusBadge } from '@/components/app-shell'

const recent = [
  { title: 'Software Engineering Internship', type: 'Internship', match: '78%', status: 'Eligible', date: 'Today', tone: 'green' as const },
  { title: 'African Technology Scholarship', type: 'Scholarship', match: '92%', status: 'Eligible', date: 'Yesterday', tone: 'green' as const },
  { title: 'Student Innovation Grant', type: 'Grant', match: '54%', status: 'Needs review', date: '2 days ago', tone: 'amber' as const },
]

export function DashboardContent({ name }: { name: string }) { return <AppShell><main className="mx-auto max-w-7xl px-5 py-9 lg:px-10 lg:py-11"><PageHeader eyebrow="Monday, September 24, 2026" title={`Good morning, ${name.split(' ')[0]}`} description="Here&apos;s what needs your attention today." /><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[['Analyses','24',FileText,'All opportunities'],['Eligible','17',CheckCircle2,'71% of analyses'],['Needs review','4',Clock3,'Worth a closer look'],['Deadlines','3',CalendarDays,'Next 30 days']].map(([label,value,Icon,detail]) => <div key={label as string} className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center justify-between"><p className="text-sm font-medium text-slate-500">{label as string}</p><span className="grid size-8 place-items-center rounded-lg bg-slate-50 text-slate-500"><Icon className="size-4" /></span></div><p className="mt-5 text-3xl font-bold tracking-tight">{value as string}</p><p className="mt-1 text-xs text-slate-400">{detail as string}</p></div>)}</div><section className="mt-8 rounded-xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-5 py-5"><div><h2 className="font-semibold">Recent analyses</h2><p className="mt-1 text-xs text-slate-400">Your latest opportunity reviews.</p></div><Link href="/analyses" className="text-sm font-semibold text-blue-600">View all</Link></div><div className="divide-y divide-slate-100">{recent.map((item) => <Link href="/analyses/1" key={item.title} className="flex items-center gap-4 px-5 py-4 hover:bg-slate-50"><span className="grid size-10 place-items-center rounded-lg bg-blue-50 text-blue-600"><FileText className="size-4" /></span><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-slate-400">{item.type} · {item.date}</p></div><StatusBadge tone={item.tone}>{item.status}</StatusBadge><span className="text-sm font-bold">{item.match}</span><ArrowUpRight className="size-4 text-slate-400" /></Link>)}</div></section></main></AppShell> }

