'use client'

import Link from 'next/link'
import { ArrowRight, Check, CheckCircle2, ChevronRight, Clock3, FileText, GraduationCap, BriefcaseBusiness, Award, ClipboardCheck, Sparkles, Upload, Menu, X } from 'lucide-react'
import { useState } from 'react'

const steps = [
  { number: '01', icon: Upload, title: 'Upload', body: 'Add a PDF, document, or opportunity description.' },
  { number: '02', icon: Sparkles, title: 'Analyze', body: 'We extract requirements, deadlines, and application steps.' },
  { number: '03', icon: ClipboardCheck, title: 'Match', body: 'See how your profile compares to what is required.' },
  { number: '04', icon: ArrowRight, title: 'Take action', body: 'Follow a clear, personalized checklist to move forward.' },
]

const features = [
  ['Requirement extraction', 'Find eligibility criteria, documents, skills, and deadlines in seconds.'],
  ['Personalized matching', 'Compare every opportunity against the profile you build.'],
  ['Gap analysis', 'See what you have, what is missing, and what needs review.'],
  ['Action plans', 'Turn dense instructions into an ordered checklist.'],
  ['Deadline tracking', 'Keep important dates visible before they become urgent.'],
  ['Saved analyses', 'Keep every opportunity and its next steps in one place.'],
]

const useCases = [
  { icon: GraduationCap, title: 'Scholarships', body: 'Know whether you qualify and exactly what documents you need.' },
  { icon: BriefcaseBusiness, title: 'Internships & jobs', body: 'Compare your skills and experience against the role.' },
  { icon: Award, title: 'Grants & competitions', body: 'Understand eligibility criteria and submission requirements.' },
  { icon: FileText, title: 'University processes', body: 'Turn institutional guidelines into clear, doable steps.' },
]

function Logo() {
  return <Link href="/" className="flex items-center gap-2.5 font-semibold tracking-tight text-[#0f172a]"><span className="grid size-8 place-items-center rounded-[9px] bg-[#0f172a] text-white"><ArrowRight className="size-4" strokeWidth={2.5} /></span><span className="text-[17px]">NextStep</span></Link>
}

function ProductPreview() {
  return <div className="relative mx-auto w-full max-w-[500px] lg:mr-0">
    <div className="absolute -inset-5 rounded-[28px] bg-blue-50/70 blur-2xl" />
    <div className="relative overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-[0_24px_70px_rgba(15,23,42,0.12)]">
      <div className="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div className="flex items-center gap-2"><div className="grid size-8 place-items-center rounded-lg bg-blue-50 text-blue-600"><FileText className="size-4" /></div><div><p className="text-[11px] font-medium text-slate-400">ANALYSIS</p><p className="text-sm font-semibold text-slate-900">Software Engineering Internship</p></div></div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700">Eligible</span></div>
      <div className="grid gap-5 p-5 sm:grid-cols-[150px_1fr]">
        <div className="flex flex-col items-center justify-center rounded-xl bg-slate-50 py-5"><div className="relative grid size-24 place-items-center rounded-full" style={{ background: 'conic-gradient(#2563eb 0 78%, #e2e8f0 78% 100%)' }}><div className="grid size-[76px] place-items-center rounded-full bg-white"><span className="text-2xl font-bold text-slate-900">78%</span></div></div><p className="mt-3 text-xs font-semibold text-slate-700">Strong match</p><p className="mt-1 text-center text-[11px] text-slate-400">Most core requirements met</p></div>
        <div><p className="mb-3 text-xs font-semibold uppercase tracking-[0.12em] text-slate-400">Eligibility</p><div className="grid gap-2.5">{['Computer Engineering', 'JavaScript', 'React', 'Git'].map((item) => <div key={item} className="flex items-center gap-2 text-xs text-slate-700"><CheckCircle2 className="size-4 text-emerald-500" />{item}</div>)}<div className="flex items-center gap-2 text-xs text-amber-700"><Clock3 className="size-4" />2+ years experience</div></div></div>
      </div>
      <div className="border-t border-slate-100 px-5 py-4"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-semibold text-slate-900">Your next steps</p><span className="text-[11px] text-slate-400">3 of 6 complete</span></div><div className="h-1.5 overflow-hidden rounded-full bg-slate-100"><div className="h-full w-1/2 rounded-full bg-blue-600" /></div><div className="mt-4 grid grid-cols-2 gap-2 text-[11px] text-slate-600"><span className="flex items-center gap-1.5"><Check className="size-3 text-emerald-500" />Prepare CV</span><span className="flex items-center gap-1.5"><Check className="size-3 text-emerald-500" />Get transcript</span><span className="flex items-center gap-1.5 text-slate-400"><span className="size-3 rounded-full border border-slate-300" />Recommendation</span><span className="flex items-center gap-1.5 text-slate-400"><span className="size-3 rounded-full border border-slate-300" />Submit application</span></div></div>
      <div className="flex items-center justify-between bg-amber-50 px-5 py-3"><span className="flex items-center gap-2 text-xs font-medium text-amber-800"><Clock3 className="size-4" />Application deadline</span><span className="text-xs font-bold text-amber-900">Sep 30 · 6 days left</span></div>
    </div>
  </div>
}

export default function Page() {
  const [mobileOpen, setMobileOpen] = useState(false)
  return <main className="min-h-screen bg-[#f8fafc] text-[#0f172a]">
    <header className="sticky top-0 z-20 border-b border-slate-200/80 bg-[#f8fafc]/90 backdrop-blur-xl"><div className="mx-auto flex h-[72px] max-w-7xl items-center justify-between px-5 lg:px-8"><Logo /><nav className="hidden items-center gap-8 text-sm text-slate-500 md:flex"><a href="#how-it-works" className="transition hover:text-slate-900">How it works</a><a href="#use-cases" className="transition hover:text-slate-900">Use cases</a><a href="#features" className="transition hover:text-slate-900">Features</a></nav><div className="hidden items-center gap-5 md:flex"><Link href="/login" className="text-sm font-medium text-slate-600 hover:text-slate-900">Sign in</Link><Link href="/analyze" className="rounded-lg bg-[#0f172a] px-4 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-[#1e293b]">Get started <ArrowRight className="ml-1 inline size-4" /></Link></div><button aria-label="Toggle menu" onClick={() => setMobileOpen(!mobileOpen)} className="rounded-lg p-2 text-slate-700 md:hidden">{mobileOpen ? <X /> : <Menu />}</button></div>{mobileOpen && <div className="border-t border-slate-200 bg-white px-5 py-4 md:hidden"><div className="flex flex-col gap-4 text-sm"><a href="#how-it-works">How it works</a><a href="#use-cases">Use cases</a><a href="#features">Features</a><Link href="/login">Sign in</Link><Link href="/analyze" className="rounded-lg bg-[#0f172a] px-4 py-2.5 text-center font-semibold text-white">Get started</Link></div></div>}</header>
    <section className="mx-auto grid max-w-7xl items-center gap-16 px-5 pb-20 pt-20 lg:grid-cols-[1fr_0.9fr] lg:px-8 lg:pb-28 lg:pt-28"><div><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-blue-100 bg-blue-50 px-3 py-1.5 text-xs font-semibold text-blue-700"><Sparkles className="size-3.5" /> Requirement intelligence, made practical</div><h1 className="max-w-2xl text-5xl font-bold leading-[1.05] tracking-[-0.055em] text-[#0b1120] sm:text-6xl">Know what you qualify for.<br /><span className="text-blue-600">Know what to do next.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-slate-500">NextStep turns complicated opportunity and process documents into personalized requirements, eligibility insights, and actionable checklists.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/analyze" className="rounded-lg bg-blue-600 px-5 py-3.5 text-center text-sm font-semibold text-white shadow-[0_8px_20px_rgba(37,99,235,0.2)] transition hover:bg-blue-700">Analyze a document <ArrowRight className="ml-1 inline size-4" /></Link><a href="#how-it-works" className="rounded-lg border border-slate-200 bg-white px-5 py-3.5 text-center text-sm font-semibold text-slate-700 transition hover:border-slate-300">See how it works</a></div><div className="mt-10 flex items-center gap-3 text-xs text-slate-400"><div className="flex -space-x-2"><span className="grid size-7 place-items-center rounded-full border-2 border-[#f8fafc] bg-blue-100 text-[10px] font-bold text-blue-700">AK</span><span className="grid size-7 place-items-center rounded-full border-2 border-[#f8fafc] bg-emerald-100 text-[10px] font-bold text-emerald-700">OS</span><span className="grid size-7 place-items-center rounded-full border-2 border-[#f8fafc] bg-amber-100 text-[10px] font-bold text-amber-700">JM</span></div><span>Built for people ready to move forward.</span></div></div><ProductPreview /></section>
    <section className="border-y border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-wrap items-center gap-3 px-5 py-6 lg:px-8"><p className="mr-3 text-sm font-medium text-slate-500">From opportunities to applications:</p>{['Scholarships','Internships','Jobs','Grants','University processes'].map((x) => <span key={x} className="rounded-full border border-slate-200 bg-slate-50 px-3.5 py-2 text-xs font-medium text-slate-600">{x}</span>)}</div></section>
    <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="max-w-xl"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-blue-600">How it works</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">Clarity in four simple steps.</h2><p className="mt-4 text-slate-500">No more rereading the same document and wondering if you missed something important.</p></div><div className="mt-12 grid gap-4 md:grid-cols-4">{steps.map(({ number, icon: Icon, title, body }) => <div key={number} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex items-center justify-between"><span className="text-sm font-bold text-blue-600">{number}</span><Icon className="size-5 text-slate-400" /></div><h3 className="mt-10 text-base font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{body}</p></div>)}</div></section>
    <section id="features" className="border-y border-slate-200 bg-white"><div className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="text-sm font-semibold uppercase tracking-[0.14em] text-blue-600">The NextStep difference</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">From information to action.</h2></div><p className="max-w-md text-sm leading-6 text-slate-500">Everything you need to make better decisions about the opportunities in front of you.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-xl border border-slate-200 bg-slate-200 sm:grid-cols-2 lg:grid-cols-3">{features.map(([title, body], i) => <div key={title} className="bg-white p-6"><span className="text-xs font-bold text-blue-600">0{i + 1}</span><h3 className="mt-8 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{body}</p></div>)}</div></div></section>
    <section id="use-cases" className="mx-auto max-w-7xl px-5 py-24 lg:px-8"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[0.14em] text-blue-600">Built for your next opportunity</p><h2 className="mt-3 text-3xl font-bold tracking-tight sm:text-4xl">One clear plan, whatever you&apos;re applying for.</h2></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{useCases.map(({ icon: Icon, title, body }) => <div key={title} className="rounded-xl border border-slate-200 bg-white p-6 transition hover:-translate-y-0.5 hover:shadow-lg"><div className="grid size-10 place-items-center rounded-lg bg-blue-50 text-blue-600"><Icon className="size-5" /></div><h3 className="mt-5 font-semibold">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{body}</p><a href="#" className="mt-5 inline-flex items-center text-xs font-semibold text-blue-600">Explore use case <ChevronRight className="ml-1 size-3.5" /></a></div>)}</div></section>
    <section className="mx-5 mb-20 overflow-hidden rounded-2xl bg-[#0f172a] lg:mx-auto lg:max-w-7xl"><div className="flex flex-col items-start justify-between gap-8 px-7 py-12 sm:px-12 sm:py-16 md:flex-row md:items-center"><div><h2 className="max-w-xl text-3xl font-bold tracking-tight text-white sm:text-4xl">Stop reading requirements.<br />Start taking action.</h2><p className="mt-4 max-w-lg text-sm leading-6 text-slate-400">Your next opportunity is easier to understand than you think.</p></div><Link href="/analyze" className="shrink-0 rounded-lg bg-white px-5 py-3.5 text-sm font-semibold text-slate-900 transition hover:bg-slate-100">Get started <ArrowRight className="ml-1 inline size-4" /></Link></div></section>
    <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col gap-5 px-5 py-8 text-sm text-slate-400 sm:flex-row sm:items-center sm:justify-between lg:px-8"><Logo /><div className="flex flex-wrap gap-5"><a href="#features" className="hover:text-slate-700">Features</a><a href="#use-cases" className="hover:text-slate-700">Use cases</a><a href="#" className="hover:text-slate-700">Privacy</a><a href="#" className="hover:text-slate-700">Contact</a></div><span>© 2026 NextStep</span></div></footer>
  </main>
}
